### ISSUE TITLE
都道府県画像をスロットみたいに上から下へシャーっと流すアニメーションを調べる

### ISSUE THREAD

**Issue by komaitaira** [Apocalyptic-Wonderboiled/wonder-app#10]
掲題の通り。なんて調べればええんやろ
![image](https://github.com/Apocalyptic-Wonderboiled/wonder-app/assets/63830279/ed82ce87-f588-4186-b190-690c7aec7dba)

ストップボタンを押したらゆっくりになってじきに止まる感じのアニメーションにもできたら良い
あわよくば適当なファイルか、App.jsでもいいので仮実装できてるとよき

**Comment by sora-uzu** [comment]
参考
https://balance.bz/magazine/category/design-dev/slotgame/
